### ISSUE TITLE
AttributeError: 'LogRecord' object has no attribute 'message'

### ISSUE THREAD

**Issue by josephkearney91** [ScrapeOps/scrapeops-scrapy-sdk#10]
User reported issue: As an FYI we've noticed that on all of our crawlers using scrapeops-scrapy==0.5.3, this error message shows very noisily in the crawl logs.

2023-10-30 16:31:13 [root] INFO: 'LogRecord' object has no attribute 'message'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/scrapeops_scrapy/core/error_logger.py", line 138, in emit
    errorMessage = record.message
AttributeError: 'LogRecord' object has no attribute 'message'

**Comment by techbro111** [comment]
Hey thanks for reporting this! I have the same issue.

**Comment by lansespirit** [comment]
Agree with the same issue.

**Comment by josephkearney91** [comment]
Should no longer be an issue if you upgrade to the latest version

**Comment by ronaldokun** [comment]
Thank you for solving the issue!
