### ISSUE TITLE
New version of scrapeOps monitoring uses different version of urllib3 that scrapy request uses

### ISSUE THREAD

**Issue by Okaca** [ScrapeOps/scrapeops-scrapy-sdk#13]
ERROR: Cannot install -r requirements.txt (line 30), -r requirements.txt (line 32), urllib3<2 and urllib3==1.26.18 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.18
    The user requested urllib3<2
    requests 2.31.0 depends on urllib3<3 and >=1.21.1
    scrapeops-scrapy 0.5.4 depends on urllib3>=2.1

[there is no common version for urllib3>=2.1 and ](https://github.com/psf/requests/issues/6432#issue-1685467871)

> **But currently requests 2.29.0 has a range bound on it: <1.27 and >=1.21.1 for urllib3.**

same issue here, cloud deploy fails because of dependencies

**Comment by josephkearney91** [comment]
Issue should be resolved with latest release which no longer requires urllib3>=2.1
