### ISSUE TITLE
Can't add spider into platform

### ISSUE THREAD

**Issue by andreyluchianic** [ScrapeOps/scrapeops-scrapy-sdk#7]
i have repository with 2 scrapy projects inside (one is very simple other one quite complex)
in install script i do install requirements of both 
after i added repository i can add simple spider but not complex one 
weird thing is that connecting trough ssh i can successfully run `scrapy list` but ui says that can't

<img width="823" alt="Screenshot 2023-05-09 at 12 23 07" src="https://user-images.githubusercontent.com/88837148/237053778-83f4f38e-f285-4df8-b3a6-9c7faeaaade9.png">
<img width="1163" alt="Screenshot 2023-05-09 at 12 20 41" src="https://user-images.githubusercontent.com/88837148/237054034-19b3a16f-6904-410f-ae14-a31ec2ee4e52.png">

**Comment by josephkearney91** [comment]
Hi there,

I would make sure you have the correct virtual environment activated when you run scrapy list.

If you manually installed all the Python modules that you need for the Scrapy project globally then it might work for you but then when the ScrapeOps dashboard first activates the virtual environment then it might still have a missing module which would cause the scrapy list command to fail. 

I need to fix the bug of the dashboard not showing the full traceback though as then you would know what is missing for the command to work correctly.
